name: jiffy
description: "Jiffy AI app Flutter frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  flutter_svg: ^2.2.3
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

