name: jiffy
description: "Jiffy AI app Flutter frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^3.0.3
  dio: ^5.7.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0
  build_runner: ^2.4.0

dependency_overrides:
  riverpod: 3.1.0

flutter:
  uses-material-design: true

