name: jiffy
description: "Jiffy AI app Flutter frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.7.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.6
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

