name: jiffy
description: "Jiffy AI app Flutter frontend"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  dio: ^5.7.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  go_router: ^17.0.1
  font_awesome_flutter: ^10.12.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  cloud_firestore: ^6.1.1
  crypto: ^3.0.7
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.11.2

dependency_overrides: 
  riverpod: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
